#!/bin/env sh
silent=false

if [ "$1" = "-silent" ]; then
	silent=true
  shift
fi

if [ $# -eq 0 ]; then
	echo "Usage: $0 [-silent] <channel_names>"
	exit 1
fi

printf '%s\n' "$@" | xargs -P15 -I {} sh -c '
	channel="$1"
  silent="$2"
	rssfeed=$(curl -sL https://www.youtube.com/@$channel | grep -oP '\''type="application/rss\+xml" title="RSS" href="\K.*?(?=")'\'' )
	if [ -n "$rssfeed" ]; then
		echo "$rssfeed"
	elif [ "$silent" = false ]; then
		echo "Channel does not exist: $channel"
	fi
' _ {} "$silent"
